kind: Deployment
apiVersion: apps/v1
metadata:  
  namespace: test
  labels:
    app: nodejs-sample
    app.kubernetes.io/component: nodejs-sample
    app.kubernetes.io/instance: nodejs-sample
    app.kubernetes.io/name: nodejs-sample
    app.kubernetes.io/part-of: sample-app
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: 14-ubi8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-sample
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-sample
        deploymentconfig: nodejs-sample
    spec:
      containers:
        - name: nodejs-sample
          image: >-
            image-registry.openshift-image-registry.svc:5000/test/nodejs-sample:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
